name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: boradesanket13/blog-post-workflow@master
        with:
          feed_list: 'https://dev.to/feed/boradesanket13, https://medium.com/feed/@boradesanket13'
